name: Java CI with Gradle

on:
  push:
    branches: [ "main", "master" ] # Adjust if your main branch has a different name
  pull_request:
    branches: [ "main", "master" ] # Adjust if your main branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin' # Popular OpenJDK distribution

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # Official Gradle action

    - name: Build with Gradle
      run: ./gradlew build

    # Optional: Upload build artifacts if needed
    # - name: Upload build reports
    #   if: failure() # Or always()
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: build-reports
    #     path: build/reports/
